RDM-3991 Update documentation
hmcts/definition-designer-api-ccdm pull request #23
Opened 2019-02-11 10:27 UTC by adr1ancho

### JIRA link (if applicable) ###

RDM-3991

### Change description ###

Update documentation, e.g. README

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2019-02-11 10:29 UTC, adr1ancho commented on README.md
>  [![codecov](https://codecov.io/gh/hmcts/ccd-definition-designer-api/branch/master/graph/badge.svg)](https://codecov.io/gh/hmcts/ccd-definition-designer-api)
This repository is not configured to publish to docker hub at the moment.  The current pipeline publishes the docker image to hmcts.azurecr.io/hmcts/ccd-definition-designer-api instead

2019-02-11 13:50 UTC, Daniel-Lam requested changes
See comment about Overview section; otherwise, the rest is OK.

2019-02-11 13:50 UTC, Daniel-Lam commented on README.md
> +A microservice for definition designer.
I think, perhaps, we could have a bit more here... something that explains what `CCD Definition Designer` is - a service that allows CRUD operations on draft Definitions.

2019-02-12 16:40 UTC, Daniel-Lam approved these changes

2019-02-12 22:27 UTC, merged